-- INSERT INTO user (name, email, password) VALUES
--     ('Sidney Moncrief', 'sid@gmail.com' ),
--     ('Jamarr Chase', 'chase@gmail.com'),
--     ('Bart Starr', 'bart@gmail.com'),
--     ('Derrick Henry', 'derrick@gmail.com');

-- INSERT INTO gamelist (game, genre, difficulty, is_priority,) VALUES
--     ('Pokemon Platinum', 'JRPG' 'medium', '35 hours' true),
--     ('Tekken 7', 'fighting', 'hard', '4 hours' false),
--     ('Final Fantasy VI', 'JRPG', 'medium', '35 hours' false),
--     ('Yakuza 0', 'action' 'easy', '32 hours' true);
